### ISSUE TITLE
[1.19.2] Hang on server start up

### ISSUE THREAD

**Issue by kwpugh** [Marwinkas/MysticalCrops#2]
Mod v1.3.5

full server log:  
[latest.log](https://github.com/Marwinkas/MysticalCrops/files/9595332/latest.log)

Client-side errors:
![Screen Shot 2022-09-18 at 4 52 45 PM](https://user-images.githubusercontent.com/8809210/190929959-1758b98d-5550-4a3c-8487-d0d076e9f905.png)

[17:01:44] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 9 out of bounds for length 9
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-1.19.2-0.14.9.jar:0.11.0]
Caused by: java.lang.IndexOutOfBoundsException: Index 9 out of bounds for length 9
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at com.google.gson.JsonArray.get(JsonArray.java:203) ~[gson-2.8.9.jar:?]
	at net.marwinka.mysticalcrops.recipe.BotanicalRitualTableRecipe$Serializer.read(BotanicalRitualTableRecipe.java:105) ~[mysticalcrops-1.3.5-1.19.2.jar:?]
	at net.marwinka.mysticalcrops.recipe.BotanicalRitualTableRecipe$Serializer.method_8121(BotanicalRitualTableRecipe.java:92) ~[mysticalcrops-1.3.5-1.19.2.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43498(class_156.java:958) ~[server-intermediary.jar:?]
	at net.minecraft.class_156.method_43499(class_156.java:946) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:156) ~[server-intermediary.jar:?]
	... 5 more

**Comment by Zacknac** [comment]
Am experiencing the same issue

**Comment by Marwinkas** [comment]
@kwpugh @Zacknac try this:
[mysticalcrops-1.3.6-1.19.2.zip](https://github.com/Marwinkas/MysticalCrops/files/9596280/mysticalcrops-1.3.6-1.19.2.zip)

**Comment by kwpugh** [comment]
Server started up with no errors.  thank you.
