### ISSUE TITLE
Any Ideas why its crashing

### ISSUE THREAD

**Issue by FizonHeXd** [Marwinkas/MysticalCrops#26]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-03-21 17:20:57
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'libgui'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: field_18792
	at io.github.cottonmc.jankson.JanksonFactory.builder(JanksonFactory.java:121)
	at io.github.cottonmc.jankson.JanksonFactory.createJankson(JanksonFactory.java:174)
	at io.github.cottonmc.cotton.gui.impl.client.LibGuiClient.<clinit>(LibGuiClient.java:24)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:459)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.2130 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.2673 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.2193 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.2486 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.2311 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.1503 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.2604 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		java.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jna9511705882605744402.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		ntdll.dll:NT Layer DLL:10.0.19041.1741 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
		win32u.dll:Win32u:10.0.19041.2728 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 4237635600 bytes (4041 MiB) / 5838471168 bytes (5568 MiB) up to 25769803776 bytes (24576 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2482
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3118
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 38493.32
	Virtual memory used (MB): 18693.73
	Swap memory total (MB): 5888.00
	Swap memory used (MB): 426.70
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx24G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ae2: Applied Energistics 2 12.9.2
			noindium: No Indium? 1.1.0+1.19
		ae2wtlib: AE2WTLib 12.8.5
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		architectury: Architectury 6.5.69
		autoswitch: AutoSwitch 5.4.7
			autoswitch-api: AutoSwitch API 3.0.0
		balm-fabric: Balm 4.5.7
		bclib: BCLib 2.1.6
		betterend: Better End 2.1.4
		betterfpsdist: Better FPS distance Mod 1.19.1-2.0
		betternether: Better Nether 7.1.3
		bettersleeping: BetterSleeping 0.6.1+1.19
			bettersleeping-core: BetterSleeping Core 0.6.1
			org_apache_commons_commons-text: commons-text 1.9
		bettertridents: Better Tridents 4.0.2
		biggerspongeabsorptionradius: Bigger Sponge Absorption Radius 3.0
		blockify: Blockify 1.2.4
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		bookshelf: Bookshelf 16.2.18
		borderlessmining: Borderless Mining 1.1.5+1.19
		botanypots: BotanyPots 9.0.28
		botanypotstiers: BotanyPotsTiers 3.3.1
		byg: Oh The Biomes You'll Go 2.0.0.13
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		carryon: Carry On 2.0.4.6
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.1
		charmofundying: Charm of Undying 6.1.1+1.19.2
		charmonium: Charmonium 4.2.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chisel: Chisel Refabricated 1.4.5
		chunky: Chunky 1.3.38
		cleancut: CleanCut 1.19.2-5.1-fabric
		clear-skies: Clear Skies 2.0.95
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+15
		collective: Collective 6.53
		connectivity: Connectivity Mod 1.19.2-3.8
		continuity: Continuity 2.0.2+1.19
		controlling: Controlling For Fabric 10.0+7
		cookingforblockheads: Cooking for Blockheads 13.3.1
		corgilib: CorgiLib 1.0.0.32
		crawl: Crawl 0.11.1
			mm: Manningham Mills 2.3
		creeper_firework: Creeper Firework 1.4.0
		creeperoverhaul: Creeper Overhaul 2.0.9
		croptopia: Croptopia 2.2.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		ctov: ChoiceTheorem's Overhauled Villages 3.1.3
		cullclouds: Cull Clouds 0.1.0
		cullleaves: Cull Leaves 3.0.1
			midnightlib: MidnightLib 1.0.0
		dashloader: DashLoader 4.1.3+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		debugify: Debugify 2.8.0
		diagonalfences: Diagonal Fences 4.2.3
		diggusmaximus: Diggus Maximus 1.5.8-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		dimthread: DimensionalThreading 1.2.7
			com_github_wearblackallday_javautils: JavaUtils bd58640372
		doomangelring: Doom Angel Ring 1.0.2
		dragonloot: DragonLoot 1.1.2
		easiervillagertrading: EasierVillagerTrading 1.19.1-fabric0.58.5-1.5.4
			gbfabrictools: GBfabrictools 1.3.4+1.19
		easyanvils: Easy Anvils 4.0.10
		eatinganimationid: Eating Animation 1.9.1
		enchdesc: EnchantmentDescriptions 13.0.14
		enhanced_quarries: Enhanced Quarries 1.19-1.2.3-alpha
			mcpitanlib: MCPitanLib 1.4.4
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		everycomp: Every Compat 1.19.2-2.2.2
		expandedstorage: Expanded Storage 8.0.5
			ellemes_container_lib: Ellemes' Container Library 2.1.0-alpha.12
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-furnaces: Fabric Furnaces 2.2.0-1.19.2
		fabric-language-kotlin: Fabric Language Kotlin 1.8.6+kotlin.1.7.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.17
		fallingleaves: Falling Leaves 1.13.0+1.19.2
		farsight: Farsight Mod 1.19-2.4
			com_github_jctools_jctools_jctools-core: jctools-core v4.0.1
		findme: FindMe 3.1.0
		fixmyspawnr: FixMySpawnR 1.1.3
		flesh2leather: Flesh2Leather 1.0.3+1.19
		forgeconfigapiport: Forge Config API Port 4.2.11
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		hudium: Hudium 1.4.5+mc1.19
			omega-config: OmegaConfig 1.3-1.19-pre5
		iceberg: Iceberg 1.0.46
		illuminations: Illuminations 1.10.11
		indium: Indium 1.0.9+mc1.19.2
		inmis: Inmis 2.7.1-1.19
		interactic: Interactic 0.1.11+1.19
		inventory_control_tweaks: Inventory Control Tweaks 1.3.19
		inventorysorter: Inventory Sorter 1.8.10-1.19
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemborders: Item Borders 1.1.6
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.6.0.1013
		jumpoverfences: Jump Over Fences 1.1.0
		jumpyboat: JumpyBoat 4.0-1.19
		keepmysoiltilled: Keep My Soil Tilled 2.0
		kibe: Kibe 1.9.11-BETA+1.19
			playerabilitylib: Pal 1.6.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		legendarytooltips: Legendary Tooltips 1.3.3
		lithium: Lithium 0.11.1
		mavm: More Axolotl Variants Mod 1.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwtrpdoors: Macaw's Trapdoors 1.0.9
		mcwwindows: Macaw's Windows 2.1.2
		measurements: Measurements 1.3.1
		megacells: MEGA Cells 2.0.0-beta.6-1.19.2
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		minecraft: Minecraft 1.19.2
		minelib: mine11lib 0.1.3+1.19
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mo_glass: Mo Glass 1.6.1-MC1.19.2
		modmenu: Mod Menu 4.2.0-beta.2
		moonlight: Moonlight 1.19.2-2.2.21
		mousetweaks: Mouse Tweaks 2.22
		mysticalcrops: Mystical Nature 1.8-1.19.2
			libgui: LibGui 6.4.0+1.19
				libninepatch: LibNinePatch 1.1.0
		nametagtweaks: Name Tag Tweaks 3.0
		netherportalfix: NetherPortalFix 10.0.1
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		npcvariety: NPC Variety 2.2.2
		offershud: OffersHUD 1.19.2-1.2.0
		oxidized: Oxidized 1.7.2
		phosphor: Phosphor 0.8.1
		pickablevillagers: Pickable Villagers 1.3.4+1.19.2
		placementpog: Bridging Mod 1.2.0
		prettybeaches: Pretty Beaches 8.0.0
		prism: Prism 1.0.3
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		reeses-sodium-options: Reese's Sodium Options 1.4.6+mc1.19.2-build.55
		resourcefulconfig: Resourcefulconfig 1.0.20
		rottencreatures: Rotten Creatures 1.0.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		seasons: Fabric Seasons 1.4-BETA+1.19
		shulkerboxtooltip: Shulker Box Tooltip 3.2.2+1.19.2
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.8.0
			libblockattributes: LibBlockAttributes 0.11.1
				libblockattributes_core: LibBlockAttributes (Core) 0.11.1
				libblockattributes_fluids: LibBlockAttributes (Fluids) 0.11.1
				libblockattributes_items: LibBlockAttributes (Items) 0.11.1
			libmultipart: LibMultiPart 0.8.0
			libnetworkstack: Lib Network Stack 0.7.1
			simple_pipes: SimplePipeTest 0.8.0
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		sod: Sod 22.10.13
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		squatgrow: Squat Grow 3.0.0-build.33+mc1.19.2
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.2.59
		techreborn: Tech Reborn 5.4.0
			reborncore: Reborn Core 5.4.0
			team_reborn_energy: Energy 2.3.0
		terrablender: TerraBlender 2.0.1.130
		the_loved_ones: The Loved Ones 1.2.0+1.19
			cotton-config: Cotton Config 1.0.0-rc.7
			cotton-logging: Cotton Logging 1.0.0-rc.4
			jankson: Jankson 4.0.0+j1.2.0
				blue_endless_jankson: jankson 1.2.1
		torcherino: Torcherino 17.0.1
		trade_cycling: Trade Cycling 1.19.2-1.0.5
		tradingpost: Trading Post 4.2.0
		trashslot: TrashSlot 12.0.2
		trinkets: Trinkets 3.4.2
		voidtotem: Void Totem 2.1.0
		wands: Building Wands 2.6.5_beta
		wondrouswilds: Wondrous Wilds 1.19.2-1.1.6
		woof: Woof 3.0.0-1.19
			owo: oωo 0.8.2+1.19
		xaerominimap: Xaero's Minimap 23.3.1
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yigd: You're in Grave Danger 1.4.8
	Launched Version: fabric-loader-0.14.17-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Marwinkas** [comment]
Mod my mod using library libgui. But it's doesn't work or incompatible with other mod. We need to think.

**Comment by Marwinkas** [comment]
Try set another fabric api version
